version: "3.9"
services:

  # [container_1] line below changed by container.py script based on container_config.yaml
  changeme1_service:
    image: ${container_1}_img_${PARENTDIR}
    container_name: ${container_1}_instance_${PARENTDIR}

    #### command to keep container alive ####
    command: /bin/bash -c "./entrypoint.sh"

    #### build Dockerfile and pass build args ####
    build:
      context: ./${container_1_folder}
      dockerfile: Dockerfile

    #### volumes and mappings ####
    volumes:
      # main container work folder mapping to host
      - ./${container_1_folder}:/root/${container_1}
      
    network_mode: "host" # uses host network stack 
    working_dir: /root/${container_1}
    
  # [container_2] line below changed by container.py script based on container_config.yaml
  changeme2_service:
    image: ${container_2}_img_${PARENTDIR}
    container_name: ${container_2}_instance_${PARENTDIR}

    #### command to keep container alive ####
    command: /bin/bash -c "./entrypoint.sh"

    #### build Dockerfile and pass build args ####
    build:
      context: ./${container_2_folder}
      dockerfile: Dockerfile

    #### volumes and mappings ####
    volumes:
      # main container work folder mapping to host
      - ./${container_2_folder}:/root/${container_2}
      
    network_mode: "host" # uses host network stack 
    working_dir: /root/${container_2}
    

  # etc... (add more services to container_config.yaml and here if you desire)